name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/akira-linux-amd64 ./cmd/akira
        GOOS=darwin GOARCH=amd64 go build -o dist/akira-darwin-amd64 ./cmd/akira
        GOOS=windows GOARCH=amd64 go build -o dist/akira-windows-amd64.exe ./cmd/akira

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: akira-binaries
        path: dist/ 