name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0

permissions:
  contents: write  # Required to upload release assets

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          mkdir -p dist
          for GOOS in linux windows darwin; do
            for GOARCH in amd64; do
              EXT=""
              if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
              BIN_NAME="akira-$GOOS-$GOARCH$EXT"
              GOOS=$GOOS GOARCH=$GOARCH go build -o dist/$BIN_NAME
            done
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
