name: Release CLI Tool

on:
  push:
    tags:
      - 'v*'  # Runs only on version tags like v1.0.0

permissions:
  contents: write  # Needed to upload release assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Binaries
        env:
          VERSION: ${{ env.VERSION }}
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          for GOOS in linux windows; do
            for GOARCH in amd64; do
              EXT=""
              if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              if [ "$GOOS" = "linux" ]; then
                BIN_NAME="akira-linux-amd64-${TIMESTAMP}"
              else
                BIN_NAME="akira-${GOOS}-${GOARCH}-${TIMESTAMP}${EXT}"
              fi
              echo "Building $BIN_NAME"
              GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-X 'main.Version=${VERSION}'" -o dist/$BIN_NAME ./cmd/akira
            done
          done
          # Include completion scripts in the release assets
          cp completion/bash_completion.sh dist/
          cp completion/zsh_completion.sh dist/
          cp completion/ps_completion.sh dist/

      - name: Generate Checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            This release includes binaries for:
            - Linux (amd64)
            - Windows (amd64)
            
            ### Installation
            
            Download the appropriate binary for your system and add it to your PATH.
            
            ### Shell Completion
            
            Bash, Zsh, and PowerShell completion scripts are included in the release assets under the `dist/` directory.
            
            ### Verification
            
            Verify the integrity of the downloaded files using the provided checksums.
          files: |
            dist/*
            dist/checksums.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
