name: Release CLI Tool

on:
  push:
    tags:
      - 'v*'  # Runs only on version tags like v1.0.0

permissions:
  contents: write  # Needed to upload release assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Binaries
        run: |
          mkdir -p dist
          for GOOS in linux windows darwin; do
            for GOARCH in amd64; do
              EXT=""
              if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
              BIN_NAME="cli-tool-${GOOS}-${GOARCH}${EXT}"
              echo "Building $BIN_NAME"
              GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-X 'main.Version=${{ env.VERSION }}'" -o dist/$BIN_NAME ./cmd/akira
            done
          done

      - name: Generate Checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
